version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-rbac-backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./app.db:/app/app.db
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./app.db
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - DEBUG=False
    restart: unless-stopped
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge

