# AI Agent Backend Docker Compose - 开发环境
# 简化的开发环境配置

version: '3.8'

services:
  # 开发环境应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-agent-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - DATABASE_URL=sqlite:///./ai_agent_dev.db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-key-for-development-only
      - LOG_LEVEL=DEBUG
      - RELOAD=True
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    depends_on:
      - redis
    networks:
      - ai-agent-dev-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Redis缓存（开发环境）
  redis:
    image: redis:7-alpine
    container_name: ai-agent-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ai-agent-dev-network

  # 数据库管理工具（可选）
  adminer:
    image: adminer
    container_name: ai-agent-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - ai-agent-dev-network

# 开发网络
networks:
  ai-agent-dev-network:
    driver: bridge
