# Web Engine 插件配置
name: web-engine
version: "1.0.0"
description: 基于 Playwright 的 Web 自动化测试引擎，支持关键字驱动和数据驱动
command: webrun
type: executor

params:
  - name: type
    label: 用例格式
    type: select
    options:
      - value: yaml
        label: YAML 格式
      - value: excel
        label: Excel 格式
    default: yaml
    help: 测试用例的格式类型

  - name: browser
    label: 浏览器类型
    type: select
    options:
      - value: chrome
        label: Chrome
      - value: firefox
        label: Firefox
      - value: edge
        label: Edge
    default: chrome
    help: 使用的浏览器类型

  - name: headless
    label: 无头模式
    type: boolean
    default: true
    help: 是否使用无头模式运行浏览器（默认 true，用户无感知）

  - name: keyDir
    label: 扩展关键字目录
    type: string
    default: ""
    help: 自定义关键字目录路径（可选）
